// GENERATED by components/intro/build-controller.mjs, do not edit.
/** Content hash of public/intro/intro.js (built from controller.js src:f8b60e7f81bb). */
export const INTRO_CONTROLLER_VERSION = "fad31d60d6";
