// GENERATED by components/intro/build-controller.mjs, do not edit.
/** Content hash of public/intro/intro.js (built from controller.js src:adcc9ad703e7). */
export const INTRO_CONTROLLER_VERSION = "d73e0e1792";
