// GENERATED by components/intro/build-controller.mjs, do not edit.
/** Content hash of public/intro/intro.js (built from controller.js src:33cb1348afa1). */
export const INTRO_CONTROLLER_VERSION = "68b6c53d88";
