// Bakes the page's SVG-filter textures to bitmaps ONCE (Chromium renders
// them, so they match what the browser drew from the live filters), so no
// feTurbulence / feGaussianBlur is recomputed at scroll time:
//   components/site/parchment-grain.ts  the Map's parchment grain (was GRAIN
//     in components/site/principles-map.tsx: fractalNoise 0.011 0.018, 3
//     octaves, seed 7, stitched), the 280 px tile as a WebP data URL (a
//     low-frequency noise: 1x is indistinguishable from 2x).
//   components/sections/act-card/frames/seam-edge-mask.ts  the IceCut's
//     feathered ragged-edge mask (was EDGE_MASK in frames/seam.tsx), as a
//     PNG data URL.
// Usage: node tools/bake/textures.js   (Chromium via the shared launcher)
const fs = require('fs');
const path = require('path');
const sharp = require('sharp');
const { launch } = require('../capture/browser');

const ROOT = path.join(__dirname, '..', '..');

const GRAIN_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="280" height="280"><filter id="g"><feTurbulence type="fractalNoise" baseFrequency="0.011 0.018" numOctaves="3" seed="7" stitchTiles="stitch"/><feColorMatrix values="0 0 0 0 0.36 0 0 0 0 0.25 0 0 0 0 0.12 0 0 0 0.1 -0.015"/></filter><rect width="100%" height="100%" filter="url(#g)"/></svg>`;

// the IceCut edge: the same deterministic points as frames/seam.tsx
function edgeLine() {
  const pts = [];
  const n = 26;
  for (let i = 0; i <= n; i++) {
    const x = (i / n) * 100;
    let h = Math.imul(i + 17, 0x9e3779b1);
    h = Math.imul(h ^ (h >>> 15), 0x85ebca77);
    const j = (((h ^ (h >>> 13)) >>> 0) % 1000) / 1000 - 0.5;
    const y = 162 - (i / n) * 24 + j * (i % 3 === 0 ? 7 : 3.5);
    pts.push([x, y]);
  }
  return pts.map(([x, y], i) => `${i ? 'L' : 'M'}${x.toFixed(2)} ${y.toFixed(2)}`).join('');
}
const EDGE_SVG = `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 300' preserveAspectRatio='none'><defs><filter id='f' x='-5%' y='-5%' width='110%' height='110%'><feGaussianBlur stdDeviation='0.25 1'/></filter></defs><path d='${edgeLine()}L100 300L0 300Z' transform='translate(0 -1.6)' fill='#fff' filter='url(#f)'/></svg>`;

const dataUrl = (svg) => `data:image/svg+xml,${encodeURIComponent(svg)}`;

async function shoot(page, svg, w, h, dpr) {
  await page.setViewportSize({ width: w, height: h });
  await page.setContent(`<!doctype html><html><body style="margin:0;background:transparent"><div id="t" style="width:${w}px;height:${h}px;background:url(&quot;${dataUrl(svg)}&quot;) 0 0/${w}px ${h}px no-repeat"></div></body></html>`);
  await page.waitForTimeout(300);
  return page.locator('#t').screenshot({ omitBackground: true, scale: 'device' });
}

(async () => {
  const { browser, release } = await launch({ headless: true });
  try {
    const lo = await (await browser.newContext({ deviceScaleFactor: 1 })).newPage();
    const grain = await shoot(lo, GRAIN_SVG, 280, 280, 1);
    const webp = await sharp(grain).webp({ quality: 85, alphaQuality: 100, effort: 6 }).toBuffer();
    fs.writeFileSync(path.join(ROOT, 'components', 'site', 'parchment-grain.ts'), `// GENERATED by tools/bake/textures.js — do not edit by hand.
// The Map's parchment grain (components/site/principles-map.tsx), baked once
// from its feTurbulence filter (seed 7) so no noise filter is recomputed
// while the walk scrolls. A 280 px tile.
export const PARCHMENT_GRAIN = "data:image/webp;base64,${webp.toString('base64')}";
`);
    console.log('grain', webp.length, 'bytes');

    const edge = await shoot(lo, EDGE_SVG, 400, 1200, 1);
    const png = await sharp(edge).png({ compressionLevel: 9, palette: false }).toBuffer();
    const ts = `// GENERATED by tools/bake/textures.js — do not edit by hand.
// The IceCut's feathered ragged edge (frames/seam.tsx), baked once from its
// feGaussianBlur SVG so the mask is never re-blurred while the card scrubs.
export const EDGE_MASK_PNG = "data:image/png;base64,${png.toString('base64')}";
`;
    const tsOut = path.join(ROOT, 'components', 'sections', 'act-card', 'frames', 'seam-edge-mask.ts');
    fs.writeFileSync(tsOut, ts);
    console.log('edge', png.length, 'bytes');
  } finally {
    await browser.close();
    release();
  }
})();
